# Generated by Django 2.2.2 on 2019-07-24 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0002_clientuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholderlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builder', to=settings.AUTH_USER_MODEL),
        ),
    ]
