# Generated by Django 2.2.2 on 2019-07-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20190726_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
