# Generated by Django 2.2.2 on 2019-07-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20190728_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='for_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_cost', to='builder.Projects'),
        ),
    ]
