# Generated by Django 2.2.2 on 2019-08-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_cost_for_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='duration',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
