# Generated by Django 2.2.2 on 2019-08-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_projects_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='total_floor',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
