# Generated by Django 2.2.2 on 2019-08-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_projects_total_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='total_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
